### ISSUE TITLE
Change iOS Deployement Target

### ISSUE THREAD

**Issue by NicolasLourenco** [jyunderwood/WaveformView-iOS#4]
Hi, 
When I install the framework via Carthage the current Deployement target is defined to iOS 10 and by the way only for arm64.

I'm obliged to make a custom build for the framework. Can you make this modification?
Thanks

**Comment by jyunderwood** [comment]
Yeah. I will get around to it soon unless you want to submit a PR.

**Comment by jyunderwood** [comment]
Deployment target removed in v2.0.3
